server:
  port: 8080
spring:
  application:
    name: hw-blockchain
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blockchain?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root